---
# https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution

- name: Add hostname-fix script on network up
  template: src=hostname-fix.j2 dest=/etc/network/if-up.d/fix-hostname mode=0755

# script itself is idempotent, so we can rely on changed_when setting
- name: Execute hostname fix
  shell: /etc/network/if-up.d/fix-hostname
  changed_when: False
