---
# Mesos Master
- include: install-mesos-master.yml
  when: mesos_mode is defined and mesos_mode == "master"

- include: run-mesos-master.yml
  when: mesos_mode is defined and mesos_mode == "master"
  tags:
    - runtime

# Mesos Agent
- include: install-mesos-agent.yml
  when: mesos_mode is defined and mesos_mode == "agent"

- include: run-mesos-agent.yml
  when: mesos_mode is defined and mesos_mode == "agent"
  tags:
    - runtime
